server:
  port: 16001
eureka:
#  server:
#    enable-self-preservation: false
#  instance:
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:16001/eureka/
spring:
  application:
    name: cloud-finchley-eureka
  profiles: default
